CREATE DATABASE airline_performance
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
USE airline_performance;

-- Create Tables
CREATE TABLE airlines (IATA_CODE CHAR(2) NOT NULL, AIRLINE VARCHAR(100) NOT NULL, PRIMARY KEY (IATA_CODE));
CREATE TABLE airports (IATA_CODE CHAR(3) NOT NULL, AIRPORT VARCHAR(150) NOT NULL, CITY VARCHAR(100), STATE CHAR(2), COUNTRY CHAR(3),
    LATITUDE  DECIMAL(9,5), LONGITUDE DECIMAL(9,5), PRIMARY KEY (IATA_CODE));
CREATE TABLE flights_staging (YEAR TEXT, MONTH TEXT, DAY TEXT, DAY_OF_WEEK TEXT, AIRLINE TEXT, FLIGHT_NUMBER TEXT, TAIL_NUMBER TEXT,
    ORIGIN_AIRPORT TEXT, DESTINATION_AIRPORT TEXT, SCHEDULED_DEPARTURE TEXT, DEPARTURE_TIME TEXT,
    DEPARTURE_DELAY TEXT, TAXI_OUT TEXT, WHEELS_OFF TEXT, SCHEDULED_TIME TEXT, ELAPSED_TIME TEXT,
    AIR_TIME TEXT, DISTANCE TEXT, WHEELS_ON TEXT, TAXI_IN TEXT, SCHEDULED_ARRIVAL TEXT, ARRIVAL_TIME TEXT,
    ARRIVAL_DELAY TEXT, DIVERTED TEXT, CANCELLED TEXT, CANCELLATION_REASON TEXT, AIR_SYSTEM_DELAY TEXT,
    SECURITY_DELAY TEXT, AIRLINE_DELAY TEXT, LATE_AIRCRAFT_DELAY TEXT, WEATHER_DELAY TEXT);
CREATE TABLE flights (YEAR INT, MONTH INT, DAY INT, DAY_OF_WEEK INT, AIRLINE VARCHAR(10), FLIGHT_NUMBER INT, TAIL_NUMBER VARCHAR(10),
    ORIGIN_AIRPORT VARCHAR(10), DESTINATION_AIRPORT VARCHAR(10), SCHEDULED_DEPARTURE INT, DEPARTURE_TIME INT,
    DEPARTURE_DELAY INT, TAXI_OUT INT, WHEELS_OFF INT, SCHEDULED_TIME INT, ELAPSED_TIME INT, AIR_TIME INT,
    DISTANCE INT, WHEELS_ON INT, TAXI_IN INT, SCHEDULED_ARRIVAL INT, ARRIVAL_TIME INT, ARRIVAL_DELAY INT,
    DIVERTED INT, CANCELLED INT, CANCELLATION_REASON VARCHAR(5), AIR_SYSTEM_DELAY INT, SECURITY_DELAY INT,
    AIRLINE_DELAY INT, LATE_AIRCRAFT_DELAY INT, WEATHER_DELAY INT);
    
-- Loading Data into Tables
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/airlines.csv'
INTO TABLE airlines FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS
(IATA_CODE, AIRLINE);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/airports.csv'
INTO TABLE airports FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS
(IATA_CODE, AIRPORT, CITY, STATE, COUNTRY, @LAT, @LON) SET LATITUDE  = NULLIF(@LAT, ''), LONGITUDE = NULLIF(@LON, '');

DROP TABLE flights_staging;

SELECT COUNT(*) FROM airlines;
SELECT COUNT(*) FROM airports;
SELECT COUNT(*) FROM flights;
SELECT COUNT(*) AS total_rows, SUM(DEPARTURE_TIME IS NULL) AS null_departure_time,
    SUM(DEPARTURE_DELAY IS NULL) AS null_departure_delay, SUM(ARRIVAL_TIME IS NULL) AS null_arrival_time,
    SUM(ARRIVAL_DELAY IS NULL) AS null_arrival_delay, SUM(CANCELLATION_REASON IS NULL AND CANCELLED = 1) 
    AS cancelled_missing_reason, SUM(AIR_SYSTEM_DELAY IS NULL) AS null_air_system_delay, SUM(AIRLINE_DELAY IS NULL) 
    AS null_airline_delay, SUM(WEATHER_DELAY IS NULL) AS null_weather_delay
FROM flights;
SELECT MIN(SCHEDULED_DEPARTURE) AS min_sched_dep, MAX(SCHEDULED_DEPARTURE) AS max_sched_dep,
    MIN(DEPARTURE_TIME) AS min_dep_time, MAX(DEPARTURE_TIME) AS max_dep_time
FROM flights;

-- Updating Table
ALTER TABLE flights ADD COLUMN flight_id INT AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE flights ADD COLUMN FLIGHT_DATE DATE AFTER DAY_OF_WEEK;
SET SQL_SAFE_UPDATES = 0;
UPDATE flights SET FLIGHT_DATE = STR_TO_DATE( CONCAT(YEAR, '-', LPAD(MONTH, 2, '0'), '-', LPAD(DAY,   2, '0')), '%Y-%m-%d');
SET SQL_SAFE_UPDATES = 1;

ALTER TABLE flights ADD COLUMN SCHEDULED_DEP_TIME TIME AFTER SCHEDULED_DEPARTURE,
ADD COLUMN ACTUAL_DEP_TIME    TIME AFTER DEPARTURE_TIME, ADD COLUMN SCHEDULED_ARR_TIME TIME AFTER SCHEDULED_ARRIVAL,
ADD COLUMN ACTUAL_ARR_TIME    TIME AFTER ARRIVAL_TIME;
DELIMITER $$
CREATE PROCEDURE update_time_columns()
BEGIN
    DECLARE i INT DEFAULT 1;
    WHILE i <= 6000000 DO
        UPDATE flights SET
            SCHEDULED_DEP_TIME = MAKETIME(FLOOR(SCHEDULED_DEPARTURE/100), MOD(SCHEDULED_DEPARTURE,100), 0),
            ACTUAL_DEP_TIME    = CASE WHEN DEPARTURE_TIME IS NOT NULL AND FLOOR(DEPARTURE_TIME/100) < 24 
                                 THEN MAKETIME(FLOOR(DEPARTURE_TIME/100), MOD(DEPARTURE_TIME,100), 0) ELSE NULL END,
            SCHEDULED_ARR_TIME = MAKETIME(FLOOR(SCHEDULED_ARRIVAL/100), MOD(SCHEDULED_ARRIVAL,100), 0),
            ACTUAL_ARR_TIME    = CASE WHEN ARRIVAL_TIME IS NOT NULL AND FLOOR(ARRIVAL_TIME/100) < 24 
                                 THEN MAKETIME(FLOOR(ARRIVAL_TIME/100), MOD(ARRIVAL_TIME,100), 0) ELSE NULL END
        WHERE flight_id BETWEEN i AND i + 499999;
        SET i = i + 500000;
    END WHILE;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 0;
CALL update_time_columns();
SET SQL_SAFE_UPDATES = 1;

SELECT SCHEDULED_DEPARTURE, SCHEDULED_DEP_TIME, DEPARTURE_TIME, ACTUAL_DEP_TIME, SCHEDULED_ARRIVAL, SCHEDULED_ARR_TIME,
    ARRIVAL_TIME, ACTUAL_ARR_TIME FROM flights LIMIT 5;

ALTER TABLE flights ADD COLUMN DEPARTURE_HOUR TINYINT UNSIGNED AFTER SCHEDULED_DEP_TIME;
DELIMITER $$
CREATE PROCEDURE update_departure_hour()
BEGIN
    DECLARE i INT DEFAULT 1;
    WHILE i <= 6000000 DO
        UPDATE flights 
        SET DEPARTURE_HOUR = HOUR(SCHEDULED_DEP_TIME)
        WHERE flight_id BETWEEN i AND i + 499999;
        SET i = i + 500000;
    END WHILE;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 0;
CALL update_departure_hour();
SET SQL_SAFE_UPDATES = 1;

SELECT SCHEDULED_DEPARTURE, SCHEDULED_DEP_TIME, DEPARTURE_HOUR FROM flights LIMIT 10;

ALTER TABLE flights ADD COLUMN IS_DELAYED TINYINT(1) NOT NULL DEFAULT 0, ADD COLUMN CANCELLATION_REASON_DESC VARCHAR(40);
DELIMITER $$
CREATE PROCEDURE update_is_delayed()
BEGIN
    DECLARE i INT DEFAULT 1;
    WHILE i <= 6000000 DO
        UPDATE flights
        SET IS_DELAYED = CASE 
            WHEN ARRIVAL_DELAY > 15 AND CANCELLED = 0 THEN 1 
            ELSE 0 END
        WHERE flight_id BETWEEN i AND i + 499999;
        SET i = i + 500000;
    END WHILE;
END$$
DELIMITER $$
CREATE PROCEDURE update_cancel_desc()
BEGIN
    DECLARE i INT DEFAULT 1;
    WHILE i <= 6000000 DO
        UPDATE flights
        SET CANCELLATION_REASON_DESC = CASE CANCELLATION_REASON
            WHEN 'A' THEN 'Airline / Carrier'
            WHEN 'B' THEN 'Weather'
            WHEN 'C' THEN 'National Air System'
            WHEN 'D' THEN 'Security'
            ELSE NULL END
        WHERE flight_id BETWEEN i AND i + 499999;
        SET i = i + 500000;
    END WHILE;
END$$
DELIMITER ;
SET SQL_SAFE_UPDATES = 0;
CALL update_is_delayed();
CALL update_cancel_desc();
SET SQL_SAFE_UPDATES = 1;

SELECT SUM(IS_DELAYED = 1) AS delayed_flights, SUM(IS_DELAYED = 0) AS on_time_flights FROM flights;
SELECT CANCELLATION_REASON, COUNT(*) AS cnt FROM flights WHERE CANCELLED = 1 GROUP BY CANCELLATION_REASON;
SELECT CANCELLATION_REASON_DESC, COUNT(*) AS total FROM flights WHERE CANCELLATION_REASON_DESC IS NOT NULL
GROUP BY CANCELLATION_REASON_DESC;

UPDATE flights
SET AIR_SYSTEM_DELAY = COALESCE(AIR_SYSTEM_DELAY, 0), SECURITY_DELAY = COALESCE(SECURITY_DELAY, 0),
    AIRLINE_DELAY = COALESCE(AIRLINE_DELAY, 0), LATE_AIRCRAFT_DELAY = COALESCE(LATE_AIRCRAFT_DELAY, 0),
    WEATHER_DELAY = COALESCE(WEATHER_DELAY, 0)
WHERE CANCELLED = 0;

SELECT FLIGHT_DATE, SCHEDULED_DEP_TIME, ACTUAL_DEP_TIME, SCHEDULED_ARR_TIME, ACTUAL_ARR_TIME, DEPARTURE_HOUR,
	   CANCELLATION_REASON, CANCELLATION_REASON_DESC, IS_DELAYED
FROM flights LIMIT 10;

-- Create Indexes
ALTER TABLE flights ADD INDEX idx_flight_date    (FLIGHT_DATE);
ALTER TABLE flights ADD INDEX idx_airline        (AIRLINE);
ALTER TABLE flights ADD INDEX idx_origin         (ORIGIN_AIRPORT);
ALTER TABLE flights ADD INDEX idx_destination    (DESTINATION_AIRPORT);
ALTER TABLE flights ADD INDEX idx_cancelled      (CANCELLED);
ALTER TABLE flights ADD INDEX idx_is_delayed     (IS_DELAYED);
ALTER TABLE flights ADD INDEX idx_month          (MONTH);
ALTER TABLE flights ADD INDEX idx_day_of_week    (DAY_OF_WEEK);
ALTER TABLE flights ADD INDEX idx_departure_hour (DEPARTURE_HOUR);
ALTER TABLE flights ADD INDEX idx_cancellation_reason (CANCELLATION_REASON);

SHOW INDEX FROM flights;

-- Create View 
DROP VIEW IF EXISTS vw_flights_enriched;
CREATE VIEW vw_flights_enriched AS
SELECT
-- Date & Time
    f.FLIGHT_DATE, f.YEAR, f.MONTH, f.DAY, f.DAY_OF_WEEK, f.DEPARTURE_HOUR, f.SCHEDULED_DEP_TIME,
    f.ACTUAL_DEP_TIME, f.SCHEDULED_ARR_TIME, f.ACTUAL_ARR_TIME,
-- Flight Identity
    f.AIRLINE AS AIRLINE_CODE, al.AIRLINE AS AIRLINE_NAME, f.FLIGHT_NUMBER, f.TAIL_NUMBER,
-- Origin Airport
    f.ORIGIN_AIRPORT AS ORIGIN_CODE, orig.AIRPORT AS ORIGIN_AIRPORT_NAME, orig.CITY AS ORIGIN_CITY,
    orig.STATE AS ORIGIN_STATE, orig.LATITUDE AS ORIGIN_LAT, orig.LONGITUDE AS ORIGIN_LON,
-- Destination Airport
    f.DESTINATION_AIRPORT AS DEST_CODE, dest.AIRPORT AS DEST_AIRPORT_NAME, dest.CITY AS DEST_CITY,
    dest.STATE AS DEST_STATE, dest.LATITUDE AS DEST_LAT, dest.LONGITUDE AS DEST_LON, f.DISTANCE,
-- Delay Metrics
    f.DEPARTURE_DELAY, f.ARRIVAL_DELAY, f.IS_DELAYED, f.AIR_SYSTEM_DELAY, f.SECURITY_DELAY, f.AIRLINE_DELAY,
    f.LATE_AIRCRAFT_DELAY, f.WEATHER_DELAY,
-- Status
    f.CANCELLED, f.CANCELLATION_REASON, f.CANCELLATION_REASON_DESC, f.DIVERTED,
-- Operational
    f.TAXI_OUT, f.TAXI_IN, f.AIR_TIME, f.ELAPSED_TIME, f.SCHEDULED_TIME
FROM flights f
LEFT JOIN airlines al   ON f.AIRLINE             = al.IATA_CODE
LEFT JOIN airports orig ON f.ORIGIN_AIRPORT      = orig.IATA_CODE
LEFT JOIN airports dest ON f.DESTINATION_AIRPORT = dest.IATA_CODE;

-- Sample of integrated view
SELECT FLIGHT_DATE, AIRLINE_NAME, ORIGIN_CITY, DEST_CITY, DEPARTURE_DELAY, ARRIVAL_DELAY, IS_DELAYED,
    CANCELLED, CANCELLATION_REASON_DESC FROM vw_flights_enriched
LIMIT 10;

-- Check view works correctly
SELECT FLIGHT_DATE, AIRLINE_NAME, ORIGIN_CITY, DEST_CITY, DEPARTURE_DELAY, ARRIVAL_DELAY, IS_DELAYED,
    CANCELLED, CANCELLATION_REASON_DESC FROM vw_flights_enriched
LIMIT 5;

SELECT COUNT(*) AS total_flights, SUM(CANCELLED) AS total_cancelled,
    ROUND(SUM(CANCELLED)/COUNT(*)*100, 2) AS cancellation_rate_pct, SUM(DIVERTED) AS total_diverted,
    SUM(IS_DELAYED) AS total_delayed, ROUND(SUM(IS_DELAYED)/NULLIF(COUNT(*)-SUM(CANCELLED),0)*100, 2)AS delay_rate_pct,
    ROUND(AVG(CASE WHEN ARRIVAL_DELAY > 0 THEN ARRIVAL_DELAY END), 2) AS avg_delay_when_delayed_min,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS avg_arrival_delay_all_min, MAX(ARRIVAL_DELAY) AS max_arrival_delay_min,
    MIN(ARRIVAL_DELAY) AS min_arrival_delay_min
FROM vw_flights_enriched;

SELECT SUM(IS_DELAYED IS NULL) AS null_is_delayed_count FROM vw_flights_enriched;

SELECT COUNT(*) AS total_flown, SUM(CASE WHEN ARRIVAL_DELAY <= 15 THEN 1 ELSE 0 END) AS on_time_flights,
    ROUND(SUM(CASE WHEN ARRIVAL_DELAY <= 15 THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS otp_rate_pct
FROM vw_flights_enriched WHERE CANCELLED = 0;

SELECT COALESCE(CANCELLATION_REASON_DESC, 'Not Cancelled') AS reason, COUNT(*) AS flight_count,
    ROUND(COUNT(*) / SUM(COUNT(*)) OVER() * 100, 2) AS pct_of_all_flights FROM vw_flights_enriched
GROUP BY CANCELLATION_REASON_DESC ORDER BY flight_count DESC;

SELECT AIRLINE_CODE, AIRLINE_NAME, COUNT(*) AS total_flights, SUM(CANCELLED) AS total_cancelled,
    ROUND(SUM(CANCELLED)/COUNT(*)*100, 2) AS cancellation_rate_pct, SUM(IS_DELAYED) AS total_delayed,
    ROUND(SUM(IS_DELAYED)/ NULLIF(COUNT(*)-SUM(CANCELLED),0)*100, 2) AS delay_rate_pct,
    ROUND(AVG(CASE WHEN CANCELLED=0 THEN ARRIVAL_DELAY END), 2) AS avg_arrival_delay_min,
    ROUND(SUM(CASE WHEN CANCELLED=0 AND ARRIVAL_DELAY <= 15 THEN 1 ELSE 0 END) /NULLIF(COUNT(*)-SUM(CANCELLED),0)*100, 2)
    AS otp_rate_pct FROM vw_flights_enriched GROUP BY AIRLINE_CODE, AIRLINE_NAME ORDER BY otp_rate_pct DESC;

SELECT MONTH, COUNT(*) AS total_flights, SUM(CANCELLED) AS total_cancelled,
    ROUND(SUM(CANCELLED)/COUNT(*)*100, 2) AS cancellation_rate_pct, SUM(IS_DELAYED) AS total_delayed,
    ROUND(SUM(IS_DELAYED)/ NULLIF(COUNT(*)-SUM(CANCELLED),0)*100, 2) AS delay_rate_pct,
    ROUND(AVG(CASE WHEN CANCELLED=0 THEN ARRIVAL_DELAY END), 2) AS avg_arrival_delay_min
FROM vw_flights_enriched GROUP BY MONTH ORDER BY MONTH;    
   
   
